### ISSUE TITLE
Querying Timestamp data issue

### ISSUE THREAD

**Issue by Chiranjeeviv** [mozilla/fxa-activity-metrics#86] opened 2017-08-31 09:58 UTC
Hi Everyone,

I am facing an issue querying data from a table by giving a condition on timestamp column, the query returning zero records, but able to see the record if I remove the condition and query with same timestamp value. 

EX: select * from table1 where start_timestmp='2017-08-24 00:00:00'; -- returning 0 records even though the table contains the data with the same value. 

The same query returning the records if I covert to text(start_timestmp::text='2017-08-24 00:00:00'). 
But the column datatype is defined as timestamp itself. Please find below. 

start_timestamp TIMESTAMP NOT NULL ENCODE lzo

Is this the issue with LZO Encode? 

Please let me know why it's behaving like this if anyone knows the reason.

Thanks !!

**Comment by shane-tomlinson** [comment] 2017-08-31 16:49
@philbooth - can you triage this?

**Comment by philbooth** [comment] 2017-09-04 11:54
Hey @Chiranjeeviv, not sure what the problem is but I doubt it is anything to do with the encoding. Might be worth reading the redshift docs on timestamps, to see if that helps:

http://docs.aws.amazon.com/redshift/latest/dg/r_Date_and_time_literals.html

Closing this issue as it has nothing to do with Firefox Accounts.

**Closed as completed by philbooth** 2017-09-04 11:54 UTC
Labels: waffle:backlog
